const express= require('express');
const app=express();
const cors= require('cors');
const dotenv= require('dotenv');
dotenv.config();
const cookieparser= require('cookie-parser');
app.use(cors());
app.use(express.json());
app.use(express.urlencoded({extended:true}));
app.use(cookieparser());
const connectToDB= require('./Database/db');
connectToDB();